import React from 'react';
import NavBar from './NavBar';
import Head from 'next/head';

export default function Layout({ children }: { children: React.ReactNode }) {
	return (
		<div>
			<NavBar />
			<br />
			<br />
			<br />
			<br />
			<br />
			<br />
			<br />
			<br />
			<Head>
				<title>ATN</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			{children}
		</div>
	);
}
